# Generated by Django 4.1.5 on 2023-01-11 09:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_baseuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="baseuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
