# Generated by Django 4.1.5 on 2023-01-11 09:46

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_baseuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="baseuser",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
