# Generated by Django 4.1.5 on 2023-01-11 13:02

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_baseuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="login_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
